# Generated by Django 4.0.4 on 2022-05-31 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_articles_article_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_description',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_title',
            field=models.CharField(max_length=150),
        ),
    ]
