# Generated by Django 4.0.4 on 2022-06-01 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_articles_article_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pic',
        ),
    ]
