# Generated by Django 3.2.13 on 2022-06-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20220609_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_author',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
