# Generated by Django 3.2.13 on 2022-06-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_articles_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_img_url',
            field=models.URLField(null=True),
        ),
    ]
