# Generated by Django 3.2.13 on 2022-06-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_articles_article_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_img_url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_url',
            field=models.URLField(max_length=500),
        ),
    ]
