# Generated by Django 3.2.13 on 2022-06-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20220610_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_img', models.ImageField(upload_to='images/')),
                ('article_author', models.CharField(max_length=250, null=True)),
                ('article_title', models.TextField()),
                ('article_description', models.TextField()),
                ('article_publish', models.DateTimeField()),
                ('reporter_condition', models.CharField(default=None, max_length=10)),
                ('editior_condition', models.CharField(default=None, max_length=20)),
                ('publisher_condition', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
