# Generated by Django 3.2.13 on 2022-06-14 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='editior_condition',
            new_name='editor_condition',
        ),
    ]
