# Generated by Django 3.2.13 on 2022-06-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_editior_condition_news_editor_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='article_publish',
            field=models.DateTimeField(null=True),
        ),
    ]
