# Generated by Django 3.2.13 on 2022-06-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_news_article_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='editor_condition',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='publisher_condition',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='reporter_condition',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
