# Generated by Django 3.2.13 on 2022-06-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20220614_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_img_url', models.URLField(max_length=500, null=True)),
                ('article_author', models.CharField(max_length=250, null=True)),
                ('article_title', models.TextField()),
                ('article_description', models.TextField()),
                ('article_url', models.URLField(max_length=500)),
                ('article_publish', models.DateTimeField()),
                ('article_category', models.CharField(max_length=50)),
            ],
        ),
    ]
