# Generated by Django 3.2.13 on 2022-06-15 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_articles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
